name: Build-Module

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - development
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main         # Push events on main branch
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ./.build.ps1 -ResolveDependency
      shell: pwsh
      name: Run script
      env:
        NuGetApiKey: ${{ secrets.NuGetApiKey }}
        GitHubKey: ${{ secrets.GITHUB_TOKEN }}
    # - name: Upload Test Results
    #   uses: actions/upload-artifact@v1.0.0
    #   if: always()
    #   with:
    #     name: testresults
    #     path: BuildOutput/testResults
    # - name: Upload Compiled module
    #   uses: actions/upload-artifact@v1.0.0
    #   if: always()
    #   with:
    #     name: compiledmodule
    #     path: BuildOutput/wrt.helpers
